image: node:14

variables:
  PUBLIC_URL: /centereddiv

cache:
  paths:
    - web/node_modules
    - web/package-lock.json

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd web/
    - npm install # Install all dependencies
    - npm run build # Build for prod
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
      - public

  only:
    - deployment
