image: node:14.17

variables:
  PUBLIC_URL: /centereddiv

cache:
  paths:
    - /node_modules
    - package-lock.json

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd web/
    - npm cache clean --force
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install # Install all dependencies
    - npm run build # Build for prod
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
      - public

  only:
    - deployment
